### ISSUE TITLE
spec iOS 13입니다.

### ISSUE THREAD

**Issue by lmk378** [naver/ntracker-sdk-ios#1]
오전 내내 고생했네요.
이런 ReadMe는 없는 것만 못합니다.
가장 찾기 어려운 오류는 매뉴얼이 잘못된 오류라 들었습니다.
수정 바랍니다.

**Comment by hongseok** [comment]
안녕하세요.

불편을 드려 죄송합니다.
문서를 업데이트 하는 과정에서 README.md 파일을 누락하여 이전 정보가 남아있었습니다.
현재 지원 버전에 맞게 iOS 13.0으로 수정하였습니다.
제보해 주셔서 감사 합니다.
