### ISSUE TITLE
Framework not found NTrackerSDKExt 에러

### ISSUE THREAD

**Issue by DongGukMon** [naver/ntracker-sdk-ios#2]
문서에서 설명한 대로 cocoapod 설치 이후 buld를 시도하면 "Framework not found NTrackerSDKExt" 에러가 발생합니다.
swift 파일에서 "import NTrackerSDK" 를 입력해도 "No such module ~" 에러가 발생합니다.

문서에서 설명한대로 따랐는데, 혹시 제가 놓치고 있는게 있을까요?

**Comment by hongseok** [comment]
안녕하세요.

두가지 이슈를 문의 하셨는데요.

1. Framework not found Error
cocoapod 설치 후에는 기존의 Project파일(.xcodeproj)이 아닌 워크스페이스 파일(.xcworkspace)을 이용해서 소스코드를 빌드해야 합니다. Project 파일을 통해 빌드하는 경우 위와같은 에러가 발생합니다.
프로젝트 구성 및 상황에 따라 정확히 저 원인이 아닐수도 있으나 흔하게 실수하는 케이스이기 때문에 이 부분을 확인해 보시면 좋을것 같습니다.

2. No such module Error
이 부분은 문서에 오류가 있었네요. 'import NTrackerSDK'가 아니라 'import NTrackerSDKExt'로 하셔야 합니다. 문서는 수정하도록 하겠습니다.
다만 위의 1번에서 말씀드린대로 정상적으로 framework이 설치되고 workspace가 로드된 상황이라면 'NTrackerSDKExt'가 자동완성으로 추천 됩니다.

<img width="460" alt="import-screenshot" src="https://github.com/naver/ntracker-sdk-ios/assets/1997644/25dbbcba-d1e1-4588-b2c7-c58e013693b8">

**Comment by DongGukMon** [comment]
1. Framework not found Error
xcworkspace 파일을 열어 빌드했음에도 발생하고 있습니다. sdk를 import해서 사용하는게 아닌, cocoapod으로 설치한 뒤에 빌드를 시도하기만 하면 발생합니다.
제 프로젝트가 React Native라서 셋팅이 이상한가 싶어 xcode로 새로운 프로젝트를 생성해 동일하게 cocoapod 설치 후 빌드를 진행해 봤지만 동일한 에러가 발생합니다.
![image](https://github.com/naver/ntracker-sdk-ios/assets/30457954/dff5c416-1c55-427c-9339-7cbd65564571)

이후 m1 아키텍쳐 문제인가 싶어서 intel mac으로 동일하게 빌드해보니 문제 없이 빌드되는 것까지 확인했습니다. 혹시 framework error가 m1 칩셋에서 발생하는 원인에 대해 추정하시고 계신 부분이 있으실까요?

**Comment by hongseok** [comment]
1. 신규 Xcode Project 생성
2. shell에서 'pod init' command를 통해 Podfile 생성
3. Podfile에 "pod 'NTrackerSDKExt'" 추가
4. shell에서 'pod install' 수행
5. xcworkspace 파일 open
6. build

이 순서로 수행 했을때 정상적으로 빌드 및 실행 되는것 확인 했습니다.
참고로 Xcode 14.3 / m1 CPU에서 수행 했습니다.

이때 생성한 프로젝트 같이 첨부 합니다.
[myexample.zip](https://github.com/naver/ntracker-sdk-ios/files/12657585/myexample.zip)

**Comment by DongGukMon** [comment]
확인 감사합니다. 제 환경에서 더 테스트 해보고 문제 해결 또는 추가 질문 사항 있으면 다시 코멘트 남기겠습니다.

**Comment by DongGukMon** [comment]
Manage Schemes... -> NTrackerSDKExt 체크 -> NTrackerSDKExt로 scheme 변경 -> build -> 빌드할 target으로 scheme 변경 후 다시 빌드

위 플로우로 진행 시 빌드 되는 것 확인했습니다. 감사합니다.

**Comment by hongseok** [comment]
이 이슈는 Close 하겠습니다. 추가로 문의사항 있으면 말씀해 주세요.
감사합니다.
